Snacks = require("snacks")

Snacks.setup({
  bigfile = { enabled = true },
  indent = { enabled = true, symbol = "┊" },
  picker = { enabled = true },
  input = { enabled = true },
  notifier = { enabled = true },
  quickfile = { enabled = true },
})

vim.ui.select = Snacks.picker.select
vim.ui.input = Snacks.input

vim.api.nvim_set_hl(0, "SnacksIndent", { fg = "#363a4f" })
vim.api.nvim_set_hl(0, "SnacksIndentScope", { fg = "#5b6078" })

-- Smart Find & Core Navigation
vim.keymap.set("n", "<leader><space>", function()
  Snacks.picker.smart()
end, { silent = true, desc = "Smart Find Files" })
vim.keymap.set("n", "<leader>,", function()
  Snacks.picker.buffers()
end, { silent = true, desc = "Buffers" })
vim.keymap.set("n", "<leader>/", function()
  Snacks.picker.grep()
end, { silent = true, desc = "Grep" })
vim.keymap.set("n", "<leader>n", function()
  Snacks.picker.notifications()
end, { silent = true, desc = "Notification History" })

-- Grep
vim.keymap.set("n", "<leader>sb", function()
  Snacks.picker.lines()
end, { silent = true, desc = "Buffer Lines" })
vim.keymap.set("n", "<leader>sB", function()
  Snacks.picker.grep_buffers()
end, { silent = true, desc = "Grep Open Buffers" })
vim.keymap.set("n", "<leader>sg", function()
  Snacks.picker.grep()
end, { silent = true, desc = "Grep" })
vim.keymap.set({ "n", "x" }, "<leader>sw", function()
  Snacks.picker.grep_word()
end, { silent = true, desc = "Visual selection or word" })

-- Search
vim.keymap.set("n", '<leader>s"', function()
  Snacks.picker.registers()
end, { silent = true, desc = "Registers" })
vim.keymap.set("n", "<leader>s/", function()
  Snacks.picker.search_history()
end, { silent = true, desc = "Search History" })
vim.keymap.set("n", "<leader>sa", function()
  Snacks.picker.autocmds()
end, { silent = true, desc = "Autocmds" })
vim.keymap.set("n", "<leader>sc", function()
  Snacks.picker.command_history()
end, { silent = true, desc = "Command History" })
vim.keymap.set("n", "<leader>sC", function()
  Snacks.picker.commands()
end, { silent = true, desc = "Commands" })
vim.keymap.set("n", "<C-S-p>", function()
  Snacks.picker.commands()
end, { silent = true, desc = "Commands" })
vim.keymap.set("n", "<leader>sd", function()
  Snacks.picker.diagnostics()
end, { silent = true, desc = "Diagnostics" })
vim.keymap.set("n", "<leader>sD", function()
  Snacks.picker.diagnostics_buffer()
end, { silent = true, desc = "Buffer Diagnostics" })
vim.keymap.set("n", "<leader>sh", function()
  Snacks.picker.help()
end, { silent = true, desc = "Help Pages" })
vim.keymap.set("n", "<leader>sH", function()
  Snacks.picker.highlights()
end, { silent = true, desc = "Highlights" })
vim.keymap.set("n", "<leader>si", function()
  Snacks.picker.icons()
end, { silent = true, desc = "Icons" })
vim.keymap.set("n", "<leader>sj", function()
  Snacks.picker.jumps()
end, { silent = true, desc = "Jumps" })
vim.keymap.set("n", "<leader>sk", function()
  Snacks.picker.keymaps()
end, { silent = true, desc = "Keymaps" })
vim.keymap.set("n", "<leader>sl", function()
  Snacks.picker.loclist()
end, { silent = true, desc = "Location List" })
vim.keymap.set("n", "<leader>sm", function()
  Snacks.picker.marks()
end, { silent = true, desc = "Marks" })
vim.keymap.set("n", "<leader>sM", function()
  Snacks.picker.man()
end, { silent = true, desc = "Man Pages" })
vim.keymap.set("n", "<leader>sn", function()
  Snacks.notifier.show_history()
end, { silent = true, desc = "Notifications" })
vim.keymap.set("n", "<leader>sq", function()
  Snacks.picker.qflist()
end, { silent = true, desc = "Quickfix List" })
vim.keymap.set("n", "<leader>sR", function()
  Snacks.picker.resume()
end, { silent = true, desc = "Resume" })
vim.keymap.set("n", "<leader>su", function()
  Snacks.picker.undo()
end, { silent = true, desc = "Undo History" })
vim.keymap.set("n", "<leader>uC", function()
  Snacks.picker.colorschemes()
end, { silent = true, desc = "Colorschemes" })

-- LSP
vim.keymap.set("n", "gd", function()
  Snacks.picker.lsp_definitions()
end, { silent = true, desc = "Goto Definition" })
vim.keymap.set("n", "gD", function()
  Snacks.picker.lsp_declarations()
end, { silent = true, desc = "Goto Declaration" })
vim.keymap.set("n", "gr", function()
  Snacks.picker.lsp_references()
end, { silent = true, desc = "References" })
vim.keymap.set("n", "gI", function()
  Snacks.picker.lsp_implementations()
end, { silent = true, desc = "Goto Implementation" })
vim.keymap.set("n", "gy", function()
  Snacks.picker.lsp_type_definitions()
end, { silent = true, desc = "Goto T[y]pe Definition" })
vim.keymap.set("n", "<leader>ls", function()
  Snacks.picker.lsp_symbols()
end, { silent = true, desc = "LSP Symbols" })
vim.keymap.set("n", "<leader>lS", function()
  Snacks.picker.lsp_workspace_symbols()
end, { silent = true, desc = "LSP Workspace Symbols" })
